@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor user
user -> Interfaz: Request a resource
Interfaz --> Servidor: Send request
database Mongo
Servidor  --> Mongo: Check resource status
Servidor  --> Mongo: Update status if available
Servidor  --> Interfaz: Return status

Interfaz --> user: Resource available or not available
@enduml